apiVersion: v1
kind: Secret
metadata:
  name: {{ include "purple-team.fullname" . }}-secrets
  labels:
    {{- include "purple-team.labels" . | nindent 4 }}
type: Opaque
stringData:
  splunk-password: {{ .Values.splunk.password | quote }}
  minio-root-user: {{ .Values.minio.rootUser | quote }}
  minio-root-password: {{ .Values.minio.rootPassword | quote }}
