apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "purple-team.fullname" . }}-splunk-data
  labels:
    app.kubernetes.io/component: splunk
    {{- include "purple-team.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.splunk.storage }}
