# Purple Team Lab — Splunk Index Configuration

[cloudtrail]
homePath   = $SPLUNK_DB/cloudtrail/db
coldPath   = $SPLUNK_DB/cloudtrail/colddb
thawedPath = $SPLUNK_DB/cloudtrail/thaweddb
maxTotalDataSizeMB = 1024
frozenTimePeriodInSecs = 604800

[vpc_flow]
homePath   = $SPLUNK_DB/vpc_flow/db
coldPath   = $SPLUNK_DB/vpc_flow/colddb
thawedPath = $SPLUNK_DB/vpc_flow/thaweddb
maxTotalDataSizeMB = 1024
frozenTimePeriodInSecs = 604800

[guardduty]
homePath   = $SPLUNK_DB/guardduty/db
coldPath   = $SPLUNK_DB/guardduty/colddb
thawedPath = $SPLUNK_DB/guardduty/thaweddb
maxTotalDataSizeMB = 512
frozenTimePeriodInSecs = 604800

[falco]
homePath   = $SPLUNK_DB/falco/db
coldPath   = $SPLUNK_DB/falco/colddb
thawedPath = $SPLUNK_DB/falco/thaweddb
maxTotalDataSizeMB = 512
frozenTimePeriodInSecs = 604800

[waf]
homePath   = $SPLUNK_DB/waf/db
coldPath   = $SPLUNK_DB/waf/colddb
thawedPath = $SPLUNK_DB/waf/thaweddb
maxTotalDataSizeMB = 512
frozenTimePeriodInSecs = 604800

[dns]
homePath   = $SPLUNK_DB/dns/db
coldPath   = $SPLUNK_DB/dns/colddb
thawedPath = $SPLUNK_DB/dns/thaweddb
maxTotalDataSizeMB = 512
frozenTimePeriodInSecs = 604800
