# Purple Team Lab — Splunk Source Type Configuration

[aws:cloudtrail]
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
TIME_PREFIX = "eventTime"\s*:\s*"
MAX_TIMESTAMP_LOOKAHEAD = 30
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
category = cloud

[aws:cloudwatchlogs:vpcflow]
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
TIME_PREFIX = "timestamp"\s*:\s*"
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
category = network

[aws:cloudwatch:guardduty]
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
TIME_PREFIX = "createdAt"\s*:\s*"
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
category = security

[falco:alerts]
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%9N%Z
TIME_PREFIX = "output_fields.evt.time"\s*:\s*"
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
category = security

[aws:waf]
TIME_FORMAT = %s%3N
TIME_PREFIX = "timestamp"\s*:\s*
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
category = web

[aws:route53:querylog]
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
TIME_PREFIX = "query_timestamp"\s*:\s*"
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TRUNCATE = 0
category = network
