# Purple Team Lab — Splunk Field Extractions

[cloudtrail_attacker_ip]
REGEX = "sourceIPAddress"\s*:\s*"([^"]+)"
FORMAT = src_ip::$1

[vpc_flow_action]
REGEX = "action"\s*:\s*"(ACCEPT|REJECT)"
FORMAT = flow_action::$1

[guardduty_severity]
REGEX = "severity"\s*:\s*(\d+\.?\d*)
FORMAT = finding_severity::$1
